// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var $clazzRadios, $generate, $taxaSelectors;
    $clazzRadios = $('#selectionpanel .clazz_selection');
    $taxaSelectors = $('#selectionpanel .taxa_selector');
    $taxaSelectors.hide();
    $clazzRadios.each(function(index, clazzRadio) {
      var $familyDD, $genusDD, $taxaDDs, $taxaRadios, $taxaSelector;
      $taxaSelector = $taxaSelectors.filter('.' + clazzRadio.value);
      $(clazzRadio).change(function(event) {
        var selectedClazz;
        $taxaSelectors.hide();
        selectedClazz = $clazzRadios.filter(':checked').prop('value');
        if (selectedClazz !== 'all') {
          return $taxaSelectors.filter('.' + selectedClazz).show('blind');
        }
      });
      if (clazzRadio.value !== 'all') {
        $taxaRadios = $taxaSelector.find('.taxa');
        $taxaDDs = $taxaSelector.find('.taxa_dd');
        $familyDD = $taxaSelector.find('.taxa_dd.family');
        $genusDD = $taxaSelector.find('.taxa_dd.genus');
        return $taxaRadios.change(function(event) {
          $taxaDDs.css('visibility', 'hidden');
          switch (event.srcElement.value) {
            case 'family':
              return $familyDD.css('visibility', 'visible');
            case 'genus':
              return $genusDD.css('visibility', 'visible');
          }
        });
      }
    });
    $generate = $('#prebakeform .generate');
    $('#prebakeform input').add('#prebakeform select').change(function(event) {
      var clazz, formIncomplete, groupName, taxaLevel;
      formIncomplete = false;
      clazz = $('#prebakeform input:radio[name="clazztype"]:checked').val();
      if ((clazz != null) && clazz !== 'all') {
        taxaLevel = $("#prebakeform input:radio[name='" + clazz + "_taxatype']:checked").val();
        if (taxaLevel !== 'all') {
          groupName = $("#prebakeform select[name='chosen_" + taxaLevel + "_" + clazz + "']").val();
          if (groupName === 'invalid') {
            formIncomplete = true;
          }
        }
      }
      return $('#prebakeform .generate').attr('disabled', formIncomplete);
    });
    return $generate.click(function(e) {
      var clazz, groupLevel, groupName, imageBounds, imageUrl, map, output, scenario, taxaLevel, year;
      year = $('#prebakeform input:radio[name="year"]:checked').val();
      scenario = $('#prebakeform input:radio[name="scenario"]:checked').val();
      output = $('#prebakeform input:radio[name="output"]:checked').val();
      clazz = $('#prebakeform input:radio[name="clazztype"]:checked').val();
      groupLevel = 'clazz';
      groupName = clazz;
      if ((clazz != null) && clazz !== 'all') {
        taxaLevel = $("#prebakeform input:radio[name='" + clazz + "_taxatype']:checked").val();
        if (taxaLevel === 'all') {

        } else {
          groupLevel = taxaLevel;
          groupName = $("#prebakeform select[name='chosen_" + taxaLevel + "_" + clazz + "']").val();
        }
      }
      console.log([year, scenario, output, groupLevel, groupName]);
      if (output === 'view') {
        $("<div class=\"popupwrapper\" style=\"display: none\">\n    <div class=\"toolbar north\"><button class=\"close\">close &times;</button></div>\n    <div id=\"popupmap\" class=\"popupmap\"></div>\n    <div class=\"toolbar south\"><button class=\"close\">close &times;</button></div>").appendTo('body').show('fade', 1000);
        $('.popupwrapper button.close').click(function(e) {
          return $('.popupwrapper').hide('fade', function() {
            return $('.popupwrapper').remove();
          });
        });
        map = L.map('popupmap', {
          minZoom: 3,
          crs: L.CRS.EPSG3395
        }).setView([-27, 135], 4);
        L.tileLayer('http://{s}.tile.cloudmade.com/831e24daed21488e8205aa95e2a14787/997/256/{z}/{x}/{y}.png', {
          attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
          maxZoom: 18
        }).addTo(map);
        imageUrl = "http://tdh-tools-1.hpc.jcu.edu.au:81/eresearch/output/MapserverImages/50878f91_512_ffffffff.png";
        imageBounds = [[-8.2687905894135, 111.9749], [-46.231165, 156.2749]];
        L.imageOverlay(imageUrl, imageBounds, {
          opacity: 0.5
        }).addTo(map);
      }
      return e.preventDefault();
    });
  });

}).call(this);
